#!/usr/bin/env bash
# script to install and configure haproxy as a load balancer

sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install haproxy -y

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

echo "frontend http_front
    bind *:80
    mode http
    default_backend http_back

backend http_back
    balance roundrobin
    server 271926-web-01 54.174.245.241:80 check
    server 271926-web-02 34.232.66.224:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "listen stats
    bind *:9000
    mode http
    stats enable
    stats uri /haproxy_stats" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart
