#!/usr/bin/env bash
# This script uses case statements
count=1

while [ ! $count -gt 20 ]
do
	echo $count
	case $count in
	4)
		echo "bad luck from China"
		;;
	9)
		echo "bad luck from Japan"
		;;
	17)
		echo "bad luck from Italy"
		;;
	esac
	((count++))
done
